// Code generated by go-bindata.
// sources:
// goja.tmpl
// DO NOT EDIT!

package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _gojaTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\x91\x3f\x4f\xc3\x30\x10\xc5\xe7\xf8\x53\x9c\xac\x0e\x09\x6a\x5d\x81\xc4\x52\xa9\x1b\x7f\x26\x4a\x55\x24\x76\x27\xbd\xba\x4e\x1b\x3b\x72\x1c\x18\xac\xfb\xee\xc8\x36\x11\x2d\x1b\x62\x3b\xdf\xbb\xf7\x7b\xa7\x73\x2f\x9b\x93\x54\x08\x21\x88\x6d\x2e\x37\xb2\x43\x22\xc6\x74\xd7\x5b\xe7\xa1\x64\x05\xff\x11\xb7\xd2\x1f\x89\x38\xab\xae\x74\xa5\xfd\x71\xac\x45\x63\xbb\xe5\xde\xf6\x77\xf7\xb7\x4b\x65\x5b\xc9\xaf\x15\x65\x95\xec\xa3\x30\x2c\xbc\xb5\xe7\x54\x25\xd0\x87\x74\x91\xd2\xd9\xfd\x78\x46\x58\x43\x14\xc4\x06\x3f\x9f\x6d\x2b\x5f\x52\xb3\xe4\xbf\xd7\xe3\x55\x74\x1e\x46\xd3\x80\x36\xda\x97\x15\x84\x89\x20\xde\xd0\x97\xac\x28\x12\xe6\xb5\x6e\xb1\xf1\x43\x60\x45\x51\x84\xb0\x80\x59\x7f\x52\x91\xb0\x5a\x5f\xf2\x60\x41\x94\x27\x9c\x34\x0a\x61\x66\xeb\x36\xf6\xe7\xa9\x7a\xc0\x83\x36\x08\xab\x35\x4c\x9e\xa7\xd1\x34\x43\xb6\xf0\x10\xa6\x69\x22\xbe\x82\x10\xa6\x08\x22\x91\xb5\xec\x27\x9a\x4f\x4b\xa0\xd9\xff\x35\xf1\x5d\xba\xff\x05\x66\x73\x6a\x55\x62\x87\x4a\x0f\x1e\x5d\x59\x31\xfa\xbe\xe2\xa3\x91\xf5\x19\x4b\x37\x1a\xaf\x3b\x84\x9b\xf8\x81\x62\x97\x5f\x97\xc7\xbd\x9e\xab\x18\x7d\x05\x00\x00\xff\xff\xf0\x06\x3b\x64\x41\x02\x00\x00")

func gojaTmplBytes() ([]byte, error) {
	return bindataRead(
		_gojaTmpl,
		"goja.tmpl",
	)
}

func gojaTmpl() (*asset, error) {
	bytes, err := gojaTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "goja.tmpl", size: 577, mode: os.FileMode(420), modTime: time.Unix(1509031864, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"goja.tmpl": gojaTmpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"goja.tmpl": &bintree{gojaTmpl, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
